### ISSUE TITLE
Is it wrong lifetime "limit"?

### ISSUE THREAD

**Issue by gordio** [ibm-watson-iot/iot-python#107]
Why?
https://github.com/ibm-watson-iot/iot-python/blob/1ad3597464ec3089837f8733b84d6fe2cb111dfc/src/ibmiotf/gateway.py#L550-L551
If in documentation reverted result: 
> If your Watson IoT Platform MQTT clients use shared subscriptions, the keep alive interval value can be set only to between 1 and 3600 seconds. If a value of 0 or a value that is greater than 3600 is requested, the Watson IoT Platform broker sets the keep alive interval to 3600 seconds.
– https://console.bluemix.net/docs/services/IoT/reference/mqtt/index.html#mqtt-keep-alive

Must be 
```python
 if lifetime > 3600: 
     lifetime = 3600 
```

**Comment by durera** [comment]
That's a rather unfortunate typo indeed, doh!

**Comment by durera** [comment]
Oh, actually .. no, having looked at the code this is something totally different to the MQTT keepalive.

`lifetime` here refers to the lifetime of a specific device management "heartbeat", that is seperate from the MQTT keepalive for the underlying MQTT connection to the platform.  

In a managed device/gateway client there is a need to regularly invoke a specific device management action to inform the platform "I'm still healthy", which is independent of whether there is an active MQTT connection for the device/gateway.  This heartbeat command must be sent to the platform on a regular interval, and if not received before the expiry time of the last one, the platform will flag the device as unhealthy. 

This is achieved by scheduling a thread that runs `manage()` on interval defined by `lifetime - 2 minutes`.  In this case we really do want to enforce a minimum value in this manner.

```
        # Register the future call back to Watson IoT Platform 2 minutes before the device lifetime expiry
        if lifetime != 0:
            threading.Timer(lifetime-120, self.manage, [lifetime, supportDeviceActions, supportFirmwareActions]).start()
```

If one tries to set a lifetime less than 1 hour, the client instead sets the lifetime as infinite, which means the platform will not assume the device is faulty ever, and no scheduling will take place in the client
