### ISSUE TITLE
Release schedule for 0.3.5

### ISSUE THREAD

**Issue by mvdfugro** [ibm-watson-iot/iot-python#119]
Dear maintainers,

We ran into issue #99 recently (Cloud Support case CS0050391), and would like to switch to a version of the library with the fix (#100) included. (we're currently using a workaround where we re-setup the library every 10k messages).  Unfortunately, 0.3.5 is not released yet -- are there any plans to release it, and if so, what is the expected timeframe?

Thanks!

**Comment by durera** [comment]
I will close out some final testing & push out what we currently have in master branch as a 0.3.5 later today :+1:

**Comment by durera** [comment]
0.3.5 is now available on pypi

**Comment by mvdfugro** [comment]
Awesome, thanks! 👍 🎉
