### ISSUE TITLE
Client.publishEvent releases _messagesLock even if not acquired

### ISSUE THREAD

**Issue by mvdfugro** [ibm-watson-iot/iot-python#122]
In `ibmiotf/application.py:377`, `_messagesLock` is acquired only if publishing was successful (`if result[0] == paho.MQTT_ERR_SUCCESS`), but it is released irrespectively in the `final:` block. This results in:

```
  File "C:\AgentWork\c2889035b7ac6605\.testenv\lib\site-packages\ibmiotf\device.py", line 307, in publishEvent
    self._messagesLock.release()
RuntimeError: release unlocked lock
```

This can happen if the client is disconnected when a message is sent (in which case paho will return `MQTT_ERR_NO_CONN`).

* This seems to have been broken accidentally as a part of https://github.com/ibm-watson-iot/iot-python/commit/ff473cead15ab9a26aa3baaea2efe1f9c8342a3c
* A simple way to reproduce this is to manually call `.disconnect()`, then call `publishEvent`.

I'm not 100% sure which code `_messagesLock` should protect; I _think_ the try-finally can be moved into the `if` statement, i.e.,

```python
                if result[0] == paho.MQTT_ERR_SUCCESS:
                    try:
                        self._messagesLock.acquire()
                        if result[1] in self._onPublishCallbacks:
                            # paho callback beat this thread so call callback inline now
                            del self._onPublishCallbacks[result[1]]
                            if on_publish is not None:
                                on_publish()
                        else:
                            # this thread beat paho callback so set up for call later
                            self._onPublishCallbacks[result[1]] = on_publish
                    finally:
                        self._messagesLock.release()
                    return True
```

**Comment by durera** [comment]
I'll put out a new release on pypi with the fixes tomorrow :+1:

**Comment by mvdfugro** [comment]
Thanks, 0.4.0 works like a charm!
