### ISSUE TITLE
IM resources API

### ISSUE THREAD

**Issue by icraggs** [ibm-watson-iot/iot-python#123]
The slack conversation snippet where we discussed this API, for reference.

David Parker [2:57 PM]
to avoid a giant object that has everything baked in the approach i was looking at was one where we compartmentalise the features somewhat ... e.g.

- api.registry only has the core stuff (device types, devices)
- api.lec is where the lec stuff comes into play (e.g. rather than `registry.devices["id"].events(eventId)` it's lec.getEvent(id, eventId)
- api,mgmt (for device mgmt stuff)
- api.things
- api.whatever
what's good structure for a rest API and good structure for the python library are not necessary equal imo, hence the approach above, that I think results in a more usable library, but that's only my opinion at the end of the day.

Ian Craggs [2:59 PM]
things = things + logical interfaces for devices too?
not sure, does it make sense to seperate them to you?  I've hardly touched all the new IM apis

Ian Craggs [3:03 PM]
things build on and use the same concepts as IM device type extensions: logical interfaces and mappings, so I think it makes sense for them to be in the same ‘component’
probably

David Parker [3:03 PM]
sounds like a good starting point, if it doesn't make sense once it starts taking shape it's easy to remould the structure if needed

Ian Craggs [3:12 PM]
So in an IM component, there could be dicts of the ‘fundamental’ resources: event types, physical interfaces, logical interfaces, schemas, and then there are relationships between those fundamental resource.    So a logical interface has to refer to a schema.  A physical interface has to refer to one or more event types, each of which has to refer to a schema.

David Parker [3:15 PM]
yeah, something like:
- api.registry.devices[id] (extends defaultdict)
- api.registry.devicetypes[id] (extends defaultdict)
- api.usage (simple object)
- api.status (simple object)
- api.lec (simple object)
- api.interfaces.eventtypes[id] (extends defaultdict)
- api.interfaces.physical[id] (extends defaultdict)
- api.interfaces.logical[id] (extends defaultdict)
- api.interfaces.schemas[id] (extends defaultdict)
- api.interfaces.things[id] (extends defaultdict)
- api.interfaces.thingtypes[id] (extends defaultdict)

or, would eventtypes and schemas fit under interfaces too? (edited)

Ian Craggs [3:16 PM]
I think they should fit under interfaces - they’re not useful outside of that context, and I don’t think that’s going to change
yes, they should definitely be grouped in an interfaces module
also api.interfaces.thingtypes and api.interfaces.things
then how to capture the relationship between objects in the different dicts?
that’s pretty much the same sort of relationship between device and devicetype
which isn’t explicitly modelled in the Python API by the looks of it
(and that can be fine)

David Parker [3:30 PM]
in the library the child relationshiup is there, but trying to avoid it' becoming a total java oo representation of the data model :slightly_smiling_face:
`api.registry.devicetypes[typeId].devices[deviceId]` works and is equivalent to `api.registry.devices[clientId]`

Ian Craggs [3:35 PM]
Ok, good.  Device types in the interface world have 1) one physical interface, 2) one or more logical interfaces and 3) a set of mappings for each logical interface.  So we could have an interfaces.devicetypes which extends registry.devicetypes and adds self.physicalInterface, self.LogicalInterfaces and self.Mappings as members?

David Parker [3:38 PM]
we can put that into the registry devicetype itself as a crossover

e.g. 
api.registry.devicetypes[typeId].interfaces.physical
api.registry.devicetypes[typeId].interfaces.logical
api.registry.devicetypes[typeId].interfaces.mappings

which can function in similar way to how the listofdevices class knows how to operate in two scopes
- api.registry.devices[id] (listofdevices extends defaultdict)

- api.registry.devicetypes[id] (listofdevicetypes extends defaultdict)
- api.registry.devicetypes[id].devices[id] (listofdevices extends defaultdict) -> type scoped version of api.registry.devices
- api.registry.devicetypes[id].interfaces.logical[id] (listoflogicalinterfaces extends defaultdict) -> type scoped version of api.interfaces.physical .. actually, does this point to a single interface, or a list
- api.registry.devicetypes[id].interfaces.physical[id] (listofphysicalinterfaces extends defaultdict) -> type scoped version of api.interfaces.logical .. actually, does this point to a single interface, or a list
- api.registry.devicetypes[id].interfaces.mappings -> *what's this?*

- api.usage (simple object)

- api.status (simple object)

- api.lec (simple object)

- api.interfaces.eventtypes[id] (extends defaultdict)
- api.interfaces.physical[id] (extends defaultdict)
- api.interfaces.logical[id] (extends defaultdict)
- api.interfaces.schemas[id] (extends defaultdict)
- api.interfaces.things[id] (extends defaultdict)
- api.interfaces.thingtypes[id] (extends defaultdict) (edited)

Ian Craggs [3:43 PM]
mappings  is a JSON object which can be set on a devicetype or thingtype, for each logical interface (edited)

Ian Craggs [4:17 PM]
when is a dictionary such as Devices(api, “mytype”) populated if at all?  getitem and contains retrieve individual devices

David Parker [4:26 PM]
Under the devicetype unit.
Devices operates in two nodes based on getting the optional scope of a devicetype
If passed, it ensures that the devices object only allows access to devices of 1 type.

Ian Craggs [5:10 PM]
so can I go a = Devices(api, “mytype”) and then print(a) and expect to see all the devices of that type?  and would it get them one at a time, or all in one HTTP call?

David Parker [5:11 PM]
for device in api.registry.devicetypes[typeid].devices:
 print(device)
You don’t instantiate the devices object directly

Use it via api.registry.devices or .devicetype.devices

**Comment by durera** [comment]
superceded by #138 and #139 ... closing this issue as remainded of deliveries are tracked in sub-issues
