### ISSUE TITLE
client commandCallback does not catch errors

### ISSUE THREAD

**Issue by edshee** [ibm-watson-iot/iot-python#124]
The example I had was where a command was being issued with format type of "JSON" but the value of the command "Data" was a string.

If an inconsistent command such as the above comes in the commandCallback is never invoked and no error is presented

**Comment by durera** [comment]
Been having a play with this, refreshing my memory of how I implemented this:  The way it should work is the `JsonCodec` should return the data of the same type that was submitted, regardless of the data type.

I've written some test cases to demonstrate this in https://github.com/ibm-watson-iot/iot-python/blob/master/test/test_codecs_json.py

It is up to the implementation of the callback handler code to decide how to handle data based on knowledge of the type of commands it expects to recieve, the framework as it is today should allow any event to pass through, as long as it's valid JSON:
- string: `"mymessage"` -- `message.data` will be a `unicode` object
- bool: `false` -- `message.data` will be a `bool` object
- int: `10` -- `message.data` will be a `int` object
- object/dict: `{"foo": "bar"}` -- `message.data` will be a `dict` object
- array/list: `["a", "b"]` -- `message.data` will be a `list` object

On review, I can't find anything in the library code that assumes data returned by the codec is of a specific type, so I think as long as the method registered as the command callback on the device client is able to deal with data in the appropriate format everything should be working fine on this front.

e.g. if your command payload can be either a set of key-vale pairs (dict) or a  string your commandcallback would need to look something like this:

```
def commandProcessor(cmd):
    if isinstance(cmd.data, unicode):
        print("Command received: %s" % cmd.data)
        # do the thing
    elif isinstance(cmd.data, dict):
        print("Command received:")
        for key in cmd.data:
            print(" - %s = %s" % (key, cmd.data[key]))
        # do the thing
    else:
        print("I don't know how to handle data of type %s" & type(cmd.data)
```

**Comment by edshee** [comment]
Thanks for looking in to this. In retrospect I realise that I never checked the server to see if it was actually sending commands where there was a mismatch in specified type and actual type. It's quite possible that the commands are never sent in that scenario and if they were then they'd pass through to the callback regardless.

I'll do some digging and confirm if that's true. Happy for you to close this off though and thanks for your help ;)
