### ISSUE TITLE
Support client connection state API

### ISSUE THREAD

**Issue by harrisondkurtz** [ibm-watson-iot/iot-python#125]
Need to create client connection state API client following the guidelines in https://github.com/ibm-watson-iot/iot-python/issues/113.

- [Link to swagger docs](https://docs.internetofthings.ibmcloud.com/apis/swagger/v0002-beta/clientstate-beta.html#/)
- [Link to WIoTP feature documentation](https://console.bluemix.net/docs/services/IoT/reference/security/client_connect.html#connect_status)

Need to ensure testcases and documentation ([style guide](https://github.com/ibm-watson-iot/iot-python/blob/master/mkdocs/docs/application/api/lec.md)) is added as well:

**Comment by durera** [comment]
Closing issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020.  See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
