### ISSUE TITLE
New state APIs appear to allow creation of Device Types

### ISSUE THREAD

**Issue by msmiths** [ibm-watson-iot/iot-python#149]
The new state APIs appear to allow the creation of Device Types, for example:

    appCli.state.active.deviceTypes.create({
        'id' : testDeviceTypeName,
       'description' : "Test Device Type description",
        'deviceInfo' : None,
        'metadata': None,
        'classId': "Device",
        'edgeConfiguration': None
    })

However, the relevant REST APIs on the Data Management component do not provide a mechanism for creating/updating/deleting Device Types.  These capabilities are provided by the Device Registry component.

**Comment by durera** [comment]
Agree, we should consolidate everything devicetype-related under registry.devicetypes, it's confusing to have two ways to work with the same resource.

**Comment by durera** [comment]
Closing issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020.  See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
