### ISSUE TITLE
del Connector.destinations[destination.name] throws ApiException despite success

### ISSUE THREAD

**Issue by robertgo-IBM** [ibm-watson-iot/iot-python#170]
`del Connector.destinations[destination.name]` throws `ApiException` despite successful removal of an Event Streams `Destination`.

Issue appears to be [here](https://github.com/ibm-watson-iot/iot-python/blob/548d2f6a0221d69d0335ecb2e62e93bcb6ab2b75/src/wiotp/sdk/api/dsc/destinations.py#L113); underlying API actually returns a status code of 204 for successful deletion of an Event Streams `Destination`:

![image](https://user-images.githubusercontent.com/32451361/63751267-eabea600-c8a6-11e9-9e5b-668779a31e94.png)

**Comment by JonahIBM** [comment]
Destinations.py was updated heavily in the new release, including the handling of the status codes - cd711a8 - let me know if this error still persists
