### ISSUE TITLE
Tokens with some characters in cause authentication errors

### ISSUE THREAD

**Issue by tim-minter** [ibm-watson-iot/iot-python#177]
During testing in simpleDevice.py with a cfg file, an authentication issue was being returned. Everything looked fine and testing with another org and device was fine. It emerged that the bracket "(" in the token generated by IBM Cloud was the cause. I guess the way this is passed in doesn't handle special characters correctly?

**Comment by JonahIBM** [comment]
Both simpleDevice and it's readme have been updated. The readme now with a more robust config format following the simpleDevice's update from the outdated ibmiotf to the current wiotp.sdk (https://github.com/ibm-watson-iot/iot-python/tree/master/samples/simpleDevice). 

This should allow for brackets in your token - I've tested it with my own with no authentication issue but let me know how it goes for you.
