### ISSUE TITLE
Unable to retrieve devices for a type using ApplicationClient / Support len() on Devices object

### ISSUE THREAD

**Issue by msmiths** [ibm-watson-iot/iot-python#178]
I have a device type created within my Organisation and I have registered a device of that type. If I attempt to use the ApplicationClient to retrieve all of the devices of that type, I get no results back.

The code that am using is as follows:

    import wiotp.sdk.application
    
    ...
    
    self.appClient = wiotp.sdk.application.ApplicationClient(appOptions)
    results = self.appClient.registry.devicetypes[typeId].devices

**Comment by durera** [comment]
in the code sample provided results will be an instance of the `Devices` object that must be used to access the devices as below:

e.g.

```
>>> devices = client.registry.devicetypes[typeId].devices
>>> print(devices)
Devices(None, {})
```

The object returned is not the list of devices, but an Object that can be used to interact with the list of devices, including implementation of a list interface.

```
>>> devices = client.registry.devicetypes["kodi"].devices
>>> print(devices)
Devices(None, {})
>>> for device in devices:
>>>  print(device)
>>>
[d:hldtxx:kodi:xx-xx-xx-xx-xx-xx] <No description>
```

More commonly, skip the assignment to `results` entirely:

```
for device in client.registry.devicetypes["kodi"].devices:
  print(device)
  # do something with the device

```

**Comment by msmiths** [comment]
@durera So, there reason that the code I am migrating from the `ibmiotf` version of the Python library is failing is that there is an **if** statement guarding the **for** loop, as follows:

    if len(devices) > 0:
        print("Devices: ", len(devices))
        for device in devices:
            deviceId = device["deviceId"]
            imutils.deleteDevice(devicetype, deviceId)

**len(devices)** is always returning 0 in with the new version of the library. Is this as expected?

**Comment by durera** [comment]
Yeah `len` won't work in this case:

for the above the equivalent is simply:

```
for device in client.registry.devicetypes[devicetype].devices:
  deviceId = device["deviceId"]
  imutils.deleteDevice(devicetype, deviceId)
```

the iterator can be safely called even if there are zero elements so there is no need to call `len()`, you will just get zero iterators of your loop performed.

Currently we can only determine the len if we iterate through all the devices and keep a count in the code.  This ensures that the code works in cases where there are potentially very large numbers of devices registered as we are only ever keeping in memory one page (from an API call) of devices at a time.  Under the covers the Devices iterator handles all the paging in the WIoTP API to present it as a seemless iterator.

Looking at our APIs, we could extend the Devices object to support the use of len() by exposing the `total_rows` metadata returned by platform APIs without needing to iterate through all the results pages.

@JonahIBM is that something you could take a look at perhaps?

**Comment by JonahIBM** [comment]
I'll take a look yeah

**Comment by durera** [comment]
Let's re-use this issue to track that, i'll update the title to reflect the proposed change

**Comment by JonahIBM** [comment]
Ignoring the accidental "revert revert revert" chain above this should be solved now.
