### ISSUE TITLE
Running multiple clients throws error

### ISSUE THREAD

**Issue by zaistev** [ibm-watson-iot/iot-python#188]
While trying to run 2 clients with 2 different API keys, I got this error
`
options = {
    "identity":{"appId":ENV_IBM_ID},
    "auth":{
    "key":ENV_IBM_AUTH_KEY,
    "token": ENV_IBM_AUTH_TOKEN
     }
}
client = wiotp.sdk.application.ApplicationClient(options)
client.connect()
client.subscribeToDeviceEvents()
client.deviceEventCallback = ...

`
When I am trying to run the second client it throws 
2020-03-25 20:48:42,216 wiotp.sdk.application.client.ApplicationClient INFO Connected successfully: XXXXX
2020-03-25 20:48:43,304 wiotp.sdk.application.client.ApplicationClient ERROR Unexpected disconnect from IBM Watson IoT

Both API keys were given the Role Backend Trusted Application.
Any suggestions that clarify why it is throwing this error? I am missing any configuration on IBM Watson IoT?

Thanks in advance.

**Comment by whitfiea** [comment]
@zaistev Are the clientIds the same for both connections? You can't make two connections with the same clientId into WIoTP.

**Comment by zaistev** [comment]
thanks @whitfiea !
silly mistake.
