### ISSUE TITLE
 Invalid Event: Received command on invalid topic: iot-2/type/Raspberrypi4B/id/pi-gateway/cmd/reset/fmt/json

### ISSUE THREAD

**Issue by fantasyhh** [ibm-watson-iot/iot-python#204]
in **appliaction.py** file:
```
commandData={'rebootDelay' : 50}
client.publishCommand("Raspberrypi4B", "pi-gateway", "reset", "json", commandData)
```
and in  **gateway_client.py**:
```
client.subscribeToCommands(commandId="resrt")
```
 gateway_client.py causes **Invalid Event: Received command on invalid topic: iot-2/type/Raspberrypi4B/id/pi-gateway/cmd/reset/fmt/json**

error in sourcecode  var command:
```
    def _onCommand(self, client, userdata, pahoMessage):
        """
        Internal callback for device command messages, parses source device from topic string and
        passes the information on to the registered device command callback
        """
        try:
            command = Command(pahoMessage, self._messageCodecs)
        except InvalidEventException as e:
            self.logger.critical(str(e))
        else:
            self.logger.debug("Received device command '%s'" % (command.commandId))
            if self.commandCallback:
                self.commandCallback(command)
```

find in Command class:

    # Raises
    InvalidEventException: If the command was recieved on a topic that does 
        not match the regular expression `iot-2/cmd/(.+)/fmt/(.+)`

`iot-2/type/Raspberrypi4B/id/pi-gateway/cmd/reset/fmt/json`  cant match `iot-2/cmd/(.+)/fmt/(.+)` ..
how to solve it?

 change another Command?

`from wiotp.sdk.gateway.messages import Notification,Command`
`# from wiotp.sdk.device.command import Command`

**Comment by durera** [comment]
First, apologies for the delay in responding to this issue.  Unfortunately due to the withdrawal of IBM Watson IoT Platform from market last year, we will not be able to address this defect in the SDK.  

See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
