### ISSUE TITLE
Publishing events on behalf of devices

### ISSUE THREAD

**Issue by Teslassian** [ibm-watson-iot/iot-python#205]
The documentation states that when applications publish on behalf of devices, publishEvent() takes up to 5 arguments: event, msgFormat, data, qos and on_publish. However, the given example has the arguments typeId, deviceId, eventId, msgFormat and data. The latter arguments definitely do not work when running the code.

See the link: https://ibm-watson-iot.github.io/iot-python/application/mqtt/events/

or the image: https://user-images.githubusercontent.com/64134453/103411155-2cd0b980-4b77-11eb-9b9e-af50c1f678ac.png

**Comment by durera** [comment]
This looks like a copy/paste error when taking the device docs as a starting point for the app docs as the typeId and deviceId params were missing from the list.

This has now been corrected: https://github.com/ibm-watson-iot/iot-python/blob/master/mkdocs/docs/application/mqtt/events.md
