### ISSUE TITLE
addDeviceType does not allow creation of gateway types

### ISSUE THREAD

**Issue by jefflowrey** [ibm-watson-iot/iot-python#21]
The addDeviceType method does not allow for the creation of gateway types.  It accepts, apparently, a parameter to specify the device class.  But it sets a default value of 'Device', and then doesn't pass this parameter to the REST call anyway - at least as far as I can see.

This requires python developers to check what kind of type they want to create, and then code a separate REST call to create a gateway type.

**Comment by jefflowrey** [comment]
Added pull request #22 with change to addDeviceType.  This should resolve this issue.

**Comment by sathipal** [comment]
Thank you @jefflowrey. Have merged the changes now.
