### ISSUE TITLE
ApiClient init needs extra parameter compared to examples

### ISSUE THREAD

**Issue by imrehg** [ibm-watson-iot/iot-python#34]
The `ApiClient` examples all use a single init variable, containing the api options, for example in `samples/apiExamples/deviceManagement.py`:
```
apiOptions = {"org": "uguhsp", "id": "myapp", "auth-method": "apikey", "auth-key": "SOME KEY", "auth-token": "SOME TOKEN"}
apiCli = ibmiotf.api.ApiClient(apiOptions)
```

On the other hand, the `ApiClient`: init definition is ` __init__(self, options, logger)`, requiring an extra parameter (`logger`), in contradiction with the examples.

**Comment by Lokesh-K-Haralakatta** [comment]
Fixed the issue in apiClient Code. The sample should work as is with this fix.
