### ISSUE TITLE
ApiClient() is not used correctly in sample files

### ISSUE THREAD

**Issue by istrate** [ibm-watson-iot/iot-python#42]
In sample you can find lines like

apiCli = ibmiotf.api.ApiClient(apiOptions)

should be 

apiCli = ibmiotf.api.ApiClient(apiOptions, logger)

Note: logger needs to be defined first and import the logging libraries

**Comment by durera** [comment]
resolved by 25cd4f5dc665ca604e9af366c7cdd82aa95cbb9b
