### ISSUE TITLE
retrieveDevices(), getAllDevices(), getAllDeviceTypes() are still used in samples 

### ISSUE THREAD

**Issue by istrate** [ibm-watson-iot/iot-python#43]
retrieveDevices(), getAllDevices(), getAllDeviceTypes() should be removed from samples and changes accordingly

**Comment by durera** [comment]
Removing all the samples under apiExample, as the single cli sample is designed to showcase all this stuff, we do not need these as well, they offer nothing beyond what is available in the docs or the CLI sample.


See: https://github.com/ibm-watson-iot/iot-python/blob/master/samples/cli/cli.py
