### ISSUE TITLE
Add XML event format support

### ISSUE THREAD

**Issue by durera** [ibm-watson-iot/iot-python#48]
- encode should take the data dictionary and convert to an XML string
- decode should take an XML string and convert to a python dictionary object
- register the new codec as the default handler for the "xml" format_string in the application, device & gateway clients
- extend the aplication.httpClient and device.httpClientto support json and xml formats instead of always using json.

**Comment by Lokesh-K-Haralakatta** [comment]
This is addressed through Merge request #52. I think, we can close this issue.
