### ISSUE TITLE
Gateway subscribes to commands for _all_ devices

### ISSUE THREAD

**Issue by bitdivision** [ibm-watson-iot/iot-python#55]
On initialisation the gateway library will subscribe to commands destined for all devices, which could become an issue with thousands of commands flying around.

https://github.com/ibm-watson-iot/iot-python/blob/master/src/ibmiotf/gateway.py#L119

Would it be more reasonable to specifically subscribe to devices for commands?

**Comment by bitdivision** [comment]
I was incorrect here, a callback is added for all devices but subcriptions are only created when `subscribeToDeviceCommands` is called.

**Comment by durera** [comment]
Agreed, gateways should follow the same rule as applications, with no default wildcarded subscriptions such as this
