### ISSUE TITLE
Application subscription issues

### ISSUE THREAD

**Issue by miketran78727** [ibm-watson-iot/iot-python#58]
In reviewing one of the Watson IoT Platform python scripts which uses this iot-python library, I would suggest to fix (or enhance) the current code for the followings:

- Error checking when subscribe (e.g. https://github.com/ibm-watson-iot/iot-python/blob/master/src/ibmiotf/application.py#L250 and https://github.com/ibm-watson-iot/iot-python/blob/master/src/ibmiotf/application.py#L269)

- Check before adding a new subscription to the subscriptions list (e.g. https://github.com/ibm-watson-iot/iot-python/blob/master/src/ibmiotf/application.py#L270  ) 

- Add on_subscribe callback which will be called when the broker responds to a subscribe request

**Comment by miketran78727** [comment]
I am working on some code and will submit a pull request for these issues.

**Comment by durera** [comment]
> Check before adding a new subscription to the subscriptions list (e.g. https://github.com/ibm-watson-iot/iot-python/blob/master/src/ibmiotf/application.py#L270 )

This has been implemented in https://github.com/ibm-watson-iot/iot-python/commit/86219b8a9d8b28e14586afd038502f7a5ad609ef

**Comment by durera** [comment]
> Error checking when subscribe (e.g. https://github.com/ibm-watson-iot/iot-python/blob/master/src/ibmiotf/application.py#L250 and https://github.com/ibm-watson-iot/iot-python/blob/master/src/ibmiotf/application.py#L269)

> Add on_subscribe callback which will be called when the broker responds to a subscribe request

These are both implemented in https://github.com/ibm-watson-iot/iot-python/commit/62f1e10232b6a962e2a746273eb77d22509a21f1

Example provided in https://github.com/ibm-watson-iot/iot-python/commit/356435f6b7c5cec97177e97c2a70e6966e67324c
