### ISSUE TITLE
paho-mqtt 1.2.1 version number breaks ibmiotf library

### ISSUE THREAD

**Issue by johnwalicki** [ibm-watson-iot/iot-python#62]
paho-mqtt 1.2.1 was released on 4 Apr 2017.   The version string "1.2.1" breaks the ibmiotf python library.

The error is in 
`/usr/lib/python2.7/site-packages/ibmiotf/__init__.py`
line 105 checks for a float but 1.2.1 is no longer a float.
`    if float(get_distribution('paho-mqtt').version) < 1.1`
`ValueError: invalid literal for float(): 1.2.1`

Here's the trace
`$ python ibm-iot-quickstart.py`
`please check the format of your config file`
`please check the format of your config file`
`Configuration file found - connecting to the registered service`
`Traceback (most recent call last):`
`  File "ibm-iot-quickstart.py", line 145, in <module>`
`    deviceClient = ibmiotf.device.Client(options)`
`  File "/usr/lib/python2.7/site-packages/ibmiotf/device.py", line 105, in __init__`
`    port = self._options['port']`
`  File "/usr/lib/python2.7/site-packages/ibmiotf/__init__.py", line 105, in __init__`
`    if float(get_distribution('paho-mqtt').version) < 1.1 and`
`(sys.version_info[0] < 3 or (sys.version_info[0] == 3 and`
`sys.version_info[1] < 2)):`
`ValueError: invalid literal for float(): 1.2.1`

**Comment by johnwalicki** [comment]
Here's a one line patch:
`Here's a patch

$ diff ./good/__init__.py ./bad/__init__.py 
31d30
< from packaging import version
106c105
< 				if version.parse(get_distribution('paho-mqtt').version) < version.parse("1.1") and (sys.version_info[0] < 3 or (sys.version_info[0] == 3 and sys.version_info[1] < 2)):
---
> 				if float(get_distribution('paho-mqtt').version) < 1.1 and (sys.version_info[0] < 3 or (sys.version_info[0] == 3 and sys.version_info[1] < 2)):`

**Comment by durera** [comment]
Removed the workaround for paho-mqtt < 1.1 entirely (requirements have stated paho-mqtt >= 1.1 for a while now anyway)

8025cc4599ec188410a188bf18938b6a41a41818
