### ISSUE TITLE
Notify Attribute Change Request tests are skipped

### ISSUE THREAD

**Issue by mzakharocsc** [ibm-watson-iot/iot-python#66]
Hello,

Can someone please clarify why  testManagedClientSetMethods() is marked as 'SkipTest' inside [test/deviceTest.py](https://github.com/ibm-watson-iot/iot-python/blob/3ad1608338b8bc8a6ae7ff661f006d568d3fc6c1/test/deviceTest.py)? 

Is [Notify Attribute Change Request](https://console.ng.bluemix.net/docs/services/IoT/devices/device_mgmt/index.html#observations-notify) API  supported?

**Comment by amprasanna** [comment]
@mzakharocsc - 'SkipTest' was mentioned against testManagedClientSetMethods() inside [test/deviceTest.py](https://github.com/ibm-watson-iot/iot-python/blob/master/test/deviceTest.py), as there was a need for internal check. 
We are working on revisiting, revising few of the tests that were scheduled to 'SkipTest' and an update shall be checked-in shortly.

Answering your query on support for  Notify Attribute Change Request API, YES, it is supported. Please refer to [Notify Attribute Changes Request](https://console.ng.bluemix.net/docs/services/IoT/devices/device_mgmt/index.html#observations-notify)
