### ISSUE TITLE
Disk Buffering feature

### ISSUE THREAD

**Issue by gfort-hoo** [ibm-watson-iot/iot-python#70]
Hi,

I would like to know if the ibmiotf library can handle disk buffering ? And if it doesn't, does anyone know what would be my best alternative ?

My use-case is that I have a device that is sending logs throughout the day, if my device loses connection and get it back later on it's fine because the unsent messages are properly stored in RAM. But if the device reboots then I lose everything.

Thanks,

**Comment by durera** [comment]
The underlying (Paho MQTT library)[https://github.com/eclipse/paho.mqtt.python] is responsible for such buffering ... you can see in the implementation here: https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L1106

```
                    # remove from inflight messages so it will be send after a connection is made
                    if rc is MQTT_ERR_NO_CONN:
                        self._inflight_messages -= 1
                        message.state = mqtt_ms_publish
```

I haven't done any specific testing of this capability, but if it turns out something in the ibmiotf library gets in the way of this function we would definitely fix that.  I'll see if we can find some time to test this specific scenario.

**Comment by gfort-hoo** [comment]
Thanks for the answer, but I still think this is not the behavior i'm looking for, because from what I understand in the code, this is to handle when the device has no connection, but the messages aren't persisted on the disk in a file, so when the device will reboot, all messages will be lost (if I get it right).

Or maybe I just didn't get at all how it works, i'll make a couple more tests to check this

**Comment by durera** [comment]
Sorry, I misread your question -- you are correct.  At the moment there is no use of disk for the message buffer today, it's in-memory so if a reboot occurs then that buffer is lost.

**Comment by amprasanna** [comment]
@gfort-hoo - Did the response from @durera on 20th of July, 2017, help address your query? Please let us know if the response is fine. If yes, let me know if it is okay to close this Issue.

**Comment by gfort-hoo** [comment]
@amprasanna - The response from @durera helped me understand that my request is not possible. Because there is no local persistence on the disk within the library, I will have to implement it myself. So I am not sure if that means you can close this issue

**Comment by amitmangalvedkar** [comment]
Closing the issue

**Comment by durera** [comment]
@gfort-hoo you should raise your requirement for disk persistence against https://github.com/eclipse/paho.mqtt.python/issues .. this is something that would be best implemented in the underlying MQTT library, as it has potential benefits across the board for a wide range of solutions.
