### ISSUE TITLE
Is it possible to use non-TLS connection?

### ISSUE THREAD

**Issue by miketran78727** [ibm-watson-iot/iot-python#71]
It seems like this library enforce TLS connection on port 8883. Is there an option to use non-TLS port 1883?

**Comment by durera** [comment]
The library uses the best available connection.  It will connect insecurely only when running on a platform where a secure connection can not be made.  When it does so it will log a warning message indicating that a secure connection was not possible.

There is no built-in option to override this logic.  Insecure connection is only available as a fallback for when a secure connection is not possible.  Advanced users _could_ force an insecure connection to be used by making changes to a few lines of code/removing the required SSL libraries if they really want to.
