### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by repoocaj** [ibm-watson-iot/iot-python#77]
There are a number of if statements where code similar to the following is executed:

```
if not self.connectEvent.wait():
    self.logger.warning("Unable ... not currently connected")
    return False
```

Those log messages can never be executed and False can never be returned.  The threading.Event wait() method always returns True unless a timeout value is given and the wait times out.  Since there is no timeout, the call will always block.
* [Python2](https://docs.python.org/2/library/threading.html#event-objects)
* [Python3](https://docs.python.org/3/library/threading.html#event-objects)

Should the wait calls be modified to something like so that the connectEvent flag is checked:

```
# The number of seconds to block for the connectEvent event to be set.
CONNECT_WAIT_SEC = 0.001

if not self.connectEvent.wait(CONNECT_WAIT_SEC):
    self.logger.warning("Unable ... not currently connected")
    return False
```

**Comment by durera** [comment]
Good spot.  I'll get this fixed for the 0.3 version being prepared at the moment.
