### ISSUE TITLE
Bring ManagedGateway capabilities like in Java package

### ISSUE THREAD

**Issue by yarharel** [ibm-watson-iot/iot-python#83]
Please add the abilities like in Java package of:
Firmware update/reset
remote commands
and more.

**Comment by amitmangalvedkar** [comment]
@yarharel : This functionality has not been implemented for devices attached to the Gateway. We are working on getting this issue resolved.

**Comment by amitmangalvedkar** [comment]
@yarharel : We are working on this functionality.   
However, check the  ```ibmiotf.gateway.ManagedClient``` class, that provides ```ManagedGateway``` functionality.  
In case that one does not address your requirements, please elaborate the requirement.

**Comment by yarharel** [comment]
@amitmangalvedkar , 
ManagedClient does provide this functionality, but we need it for the Gateway as our Device is not capable of generating a connection to WIOT by itself.

**Comment by durera** [comment]
@amitmangalvedkar what's the latest on this, there hasn't been any update since you stated you were working on this 3 months ago?

**Comment by amitmangalvedkar** [comment]
@durera : The upcoming sprint has been marked for the updates.

**Comment by yarharel** [comment]
Any news regarding this functionality?

**Comment by istrate** [comment]
@durera do you know if this was delivered?

**Comment by durera** [comment]
Sadly not, I'm going to find someone in development team to work on this :+1:

**Comment by gordio** [comment]
_Also I know Issue with ManagedGateway. Something looking like race condition or forgetting to keep `supportDeviceActions` & `supportFirmwareActions` settings in next requests… In debug I see False (actual must be True)._

**Comment by durera** [comment]
With the restructure made as part of wiotp-sdk 0.9 release the gateway client was drastically changed to a better design where it now extends the managed device client and adds gateway capabilities on top of it, this brings parity to the supported features for managed gateway and device clients in this library.
