### ISSUE TITLE
Not receiving gateway commands after "Unexpected disconnect"

### ISSUE THREAD

**Issue by keomabrun** [ibm-watson-iot/iot-python#86]
### Step to reproduce
- Run the gatewaySubscribeCommand.py with valid gateway options and wait for the `Connected successfully` message
Note: Here you can send a Gateway Command. You should receive it. Everything works.
- Block the Internet connection (e.g firewall) and wait for the `Unexpected disconnect` message (>1m)
- Unblock the Internet connection and wait for the `Connected successfully` message

When we are in that state, we don't receive the Gateway Commands anymore.

**Comment by durera** [comment]
If you set logging to debug levels do you see the subscriptions being re-established by the `on_connect` method, as each time the client connects it is explicitly subscribing to the topics for itself:

From ibmiotf.gateway.ManagedClient.on_connect():
```
                dm_response_topic = ManagedClient.DM_RESPONSE_TOPIC_TEMPLATE %  (self._gatewayType,self._gatewayId)
                dm_observe_topic = ManagedClient.DM_OBSERVE_TOPIC_TEMPLATE %  (self._gatewayType,self._gatewayId)
                self.client.subscribe( [(dm_response_topic, 1), (dm_observe_topic, 1), (self.COMMAND_TOPIC, 1)] )
```

Currently the gateway implementation doesn't restore additional subscriptions that have been made (ie, the same way the application client does) .. is that perhaps what you mean here .. that your gateway on reconnect is no longer receiving messages for devices that the gateway previously had subscribed to notifications from?

**Comment by keomabrun** [comment]
Yes, this is what I meant. I will change the debug level and give you the output. Thank you.

**Comment by durera** [comment]
Thanks .. no need for the debug now -- that clarification is all the information I need as I can see why the latter does not work.  

A fix for this won't be included in the next release that will be published later today, but I'll find someone on the team (or do it myself if necessary) to get this fixed in the next week for you.

**Comment by durera** [comment]
Notes for future self (or whoever fixes this):

Need to transplant the subscription restoration code already added to the application client into the gateway client: 

init:
```
        # If we are disconnected we lose all our active subscriptions.  Keep track of all subscriptions
        # so that we can internally restore all subscriptions on reconnect
        self._subscriptions = {}
```


on_connect:
```
            # Restoring previous subscriptions
            if len(self._subscriptions) > 0:
                for subscription in self._subscriptions:
                    self.client.subscribe(subscription, qos=self._subscriptions[subscription])
                self.logger.debug("Restored %s previous subscriptions" % len(self._subscriptions))
```

Anytime we make a subscription:
```
            (result, mid) = self.client.subscribe(topic, qos=qos)
            if result == paho.MQTT_ERR_SUCCESS:
                self._subscriptions[topic] = qos
                return mid
            else:
                return 0
```

with slight tweaks to the logic to handle that the gateway already has a set of prefedined "I always make these subscriptions too", while also adding support for the new `subscriptionCallback` handler that was added to application client in https://github.com/ibm-watson-iot/iot-python/commit/62f1e10232b6a962e2a746273eb77d22509a21f1

**Comment by keomabrun** [comment]
Thank you !

**Comment by durera** [comment]
Release 0.3.3 has a first pass at porting the resubscribe logic to both gateway and managedGateway clients.

**Comment by durera** [comment]
The porting of this functionality to gateway clients works based on my ( albeit limited:) ) testing, so closing this issue now 👍
