### ISSUE TITLE
Incorrect wildcard protection for quickstart subscribes

### ISSUE THREAD

**Issue by benbakowski** [ibm-watson-iot/iot-python#89]
In application.py:

        if self._options['org'] == "quickstart" and deviceId == "+":
            self.logger.warning("QuickStart applications do not support wildcard subscription to events from all devices")
return False

However, [https://console.bluemix.net/docs/services/IoT/applications/mqtt.html#mqtt:](https://console.bluemix.net/docs/services/IoT/applications/mqtt.html#mqtt:) states that wildcard subscribes are forbidden for deviceTypes, not deviceIds.

**Comment by CaroMac** [comment]
Have updated https://console.bluemix.net/docs/services/IoT/applications/mqtt.html#mqtt , changing deviceType to device_id in Quickstart section

**Comment by benbakowski** [comment]
To clarify this issue: the python code was correct, but documentation of the platform was misleading. We have corrected the documentation. No changes are needed to the python libraries.
