### ISSUE TITLE
Python 3.6 - Error in paho-mqtt port type

### ISSUE THREAD

**Issue by Patataman** [ibm-watson-iot/iot-python#90]
I'm using: 

- Python 3.6.3
- IBMIoT 0.3.1 (latest)
- paho-mqtt 1.3.1

In a RaspberryPi 3 (4.9.67-v7 latest kernel if I'm not wrong)

The problem is this:
```
Python 3.6.3 (default, Dec 14 2017, 14:47:50) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ibmiotf import gateway
>>> gatewayOptions = gateway.ParseConfigFile("path")
>>> rasp = gateway.Client(gatewayOptions)    
>>> rasp.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/ibmiotf/__init__.py", line 135, in connect
    self.client.connect(self.address, port=self.port, keepalive=self.keepAlive)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 767, in connect
    self.connect_async(host, port, keepalive, bind_address)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 823, in connect_async
    if port <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'

```

In Python2.7 I didn't have any problem using the library.

Looking the code (from ibmiotf/\_\_init__.py), I can't see any place where the port value is different from an integer, but for some reason in client.py it's a string, not an int.

I temporally fix it casting `port` to `int` in the `self.client.connect` call in \_\_init__.py, but somewhere must be a problem either in ibmiotf or paho-mqtt

**Comment by durera** [comment]
Looking at the code this morning there are at least two seperate problems to address here where `self.port` may end up as a string ...

`port = parms.get(sectionHeader, "port")` should be `port = parms.getint(sectionHeader, "port")`

and 

```
    parms = configparser.ConfigParser({
        "domain": "internetofthings.ibmcloud.com",
        "port": 8883,
        "clean-session": "true"
    })
```
should be 
```
    parms = configparser.ConfigParser({
        "domain": "internetofthings.ibmcloud.com",
        "port": 8883,
        "clean-session": "true"
    })
```
