### ISSUE TITLE
missing check for duplicates when appending to _subscriptions list in application client

### ISSUE THREAD

**Issue by mcdonnibm** [ibm-watson-iot/iot-python#93]
Our application creates a client using iot-python/src/ibmiotf/application.py.  It then periodicallly, creates a connection and subscribes to a topic using subscribeToDeviceEvents().  (In each of these subscribe requests, the application specifices the same topic.) After receiving messages, the client is disconnected.

We are finding that on each successive call to subscribeToDeviceEvents(), additional subscribe requests are received by the MQTT server.  It looks like this is because each time subscribe() is called in subscribeToDeviceEvents(), the topic/qos for the request are added to the _subscriptions list.  It seems that before appending a given topic/qos to this list, the application client should check first to see whether the subscription is already in the list.

**Comment by mcdonnibm** [comment]
Suggested fix.  In subscribeToDeviceEvents()

Change:
        else:
            topic = 'iot-2/type/%s/id/%s/evt/%s/fmt/%s' % (deviceType, deviceId, event, msgFormat)
            self.client.subscribe(topic, qos=qos)
            self._subscriptions.append({"topic": topic, "qos": qos})
            return True

To: 
        else:
            topic = 'iot-2/type/%s/id/%s/evt/%s/fmt/%s' % (deviceType, deviceId, event, msgFormat)
            self.client.subscribe(topic, qos=qos)
            sub = {"topic": topic, "qos": qos}
            if sub not in self._subscriptions:
                self._subscriptions.append(sub)
            return True

**Comment by durera** [comment]
Subscriptions are now stored in a map, ensuring uniqueness while allowing a latter subscription at a different qos level to change the stored qos for the subscription so that it will be restored at the most recently requested level on reconnect:

```
_subscriptions = {
  topic1: qos
  topic2: qos
}
```
