### ISSUE TITLE
How disable the creation of the log files?

### ISSUE THREAD

**Issue by CarlosCordoba96** [ibm-watson-iot/iot-python#98]
When I am testing my code so much log files are created, how can i disable this creation of the files? # @

**Comment by icraggs** [comment]
You can use the logHandlers parameter when creating the client, like this:

deviceCli = ibmiotf.device.Client(deviceOptions, logHandlers=[logging.StreamHandler()])

If you want to have the messages just written to stdout, but not a file, use a StreamHandler.

If you want no messages at all, you can use the NullHandler:

deviceCli = ibmiotf.device.Client(deviceOptions, logHandlers=[logging.NullHandler()])

**Comment by durera** [comment]
Yup, as @icraggs stated the clients (application and device) support configurable logging.

If no logHandlers are provided the default behaviour is to set up:

1. A rotating log file (limited to 1mb log file)
```
rfh = RotatingFileHandler(logFileName, mode='a', maxBytes=1024000 , backupCount=0, encoding=None, delay=True)
            rfh.setFormatter(fhFormatter)
```

2. Logging to std out:
```
ch = logging.StreamHandler()
            ch.setFormatter(fhFormatter)
```

----

To only log to std out:
```
import logging

deviceCli = ibmiotf.device.Client(deviceOptions, logHandlers=[logging.StreamHandler()])
appCli = ibmiotf.application.Client(appOptions, logHandlers=[logging.StreamHandler()])
```

For completely silent operation:
```
import logging

deviceCli = ibmiotf.device.Client(deviceOptions, logHandlers=[logging.NullHandler()])
appCli = ibmiotf.application.Client(appOptions, logHandlers=[logging.NullHandler()])
```
